# Generated by Django 5.0.3 on 2024-04-02 23:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookATable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('customer_email', models.EmailField(max_length=254)),
                ('numberOfPeople', models.IntegerField()),
                ('dateOfBooking', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.IntegerField()),
                ('cuisine_name', models.CharField(max_length=245)),
                ('price', models.FloatField()),
                ('alcohol_content', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
                ('ordered_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine_id', to='home.cuisine')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine_customer_name', to='home.cuisine')),
                ('customer_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisine_customer_phone', to='home.cuisine')),
            ],
        ),
    ]
