# Generated by Django 5.0.3 on 2024-04-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='customer_phone',
            field=models.CharField(max_length=244),
        ),
    ]
