# Generated by Django 4.2.13 on 2024-06-16 08:05

import cked.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefdetails',
            name='description',
            field=cked.fields.RichTextField(),
        ),
    ]
