# Generated by Django 4.2.13 on 2024-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='header_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='chefdetails',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
