# Generated by Django 4.2.13 on 2024-06-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_chefdetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefdetails',
            name='description',
            field=models.CharField(max_length=244),
        ),
    ]
