# Generated by Django 4.2.13 on 2024-08-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blogdetails_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='header_image',
            field=models.CharField(max_length=224),
        ),
        migrations.AlterField(
            model_name='chefdetails',
            name='image',
            field=models.CharField(max_length=244),
        ),
    ]
