# Generated by Django 5.0.3 on 2024-04-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_cuisine_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='order_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
