# Generated by Django 4.2.13 on 2024-06-18 06:37

import cked.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_chefdetails_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetails',
            name='description',
            field=cked.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chefdetails',
            name='description',
            field=cked.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=cked.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_description',
            field=cked.fields.RichTextField(),
        ),
    ]
