# Generated by Django 5.0.3 on 2024-04-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cuisine_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
