# Generated by Django 4.2.13 on 2024-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blogdetails_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.FloatField(choices=[(1.0, '1 Star'), (2.0, '2 Stars'), (3.0, '3 Stars'), (4.0, '4 Stars'), (5.0, '5 Stars')], default=5.0),
        ),
    ]
