# Generated by Django 4.2.13 on 2024-06-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_usersuggestions_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
