# Generated by Django 4.2.13 on 2024-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_cartitem_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='accept_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='message',
            field=models.CharField(default='Please Wait! We are processing your Order', max_length=200),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='reject_button',
            field=models.BooleanField(default=False),
        ),
    ]
