# Generated by Django 4.2.13 on 2024-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_cartitem_accept_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
